### ISSUE TITLE
Watchlist action will not initialize once pressed once. 

### ISSUE THREAD

**Issue by ghost** [ariaslabs/bitwatcher#1]
`[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.`

This is the error provided. I believe it's due to the state *watchlist being updated twice.

**Comment by ariaslabs** [comment]
When select the watchlist button in the Watchlist page, page does not delete the watchlist item from page, Will add Delete button to Watchlist page and to update and refresh the items.
